# Generated by Django 6.0.4 on 2026-04-29 03:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NurseDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurse_name', models.CharField(default='Nurse A', max_length=100)),
                ('watch_status', models.CharField(default='Active', max_length=20)),
                ('battery_level', models.IntegerField(default=85)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('bed_no', models.CharField(max_length=20, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('risk_level', models.CharField(choices=[('Normal', 'Normal'), ('Moderate', 'Moderate'), ('High Risk', 'High Risk')], default='Normal', max_length=20)),
                ('diagnosis', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=80)),
                ('message', models.TextField()),
                ('severity', models.CharField(max_length=20)),
                ('priority', models.IntegerField()),
                ('assigned_to', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Cleared', 'Cleared')], default='Active', max_length=20)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('response_seconds', models.IntegerField(blank=True, null=True)),
                ('action_taken', models.CharField(blank=True, max_length=150)),
                ('medication_given', models.CharField(blank=True, max_length=150)),
                ('remarks', models.TextField(blank=True)),
                ('escalation_level', models.IntegerField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Vital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField()),
                ('spo2', models.IntegerField()),
                ('bp_systolic', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('saline_level', models.IntegerField()),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.patient')),
            ],
        ),
    ]
