# Generated by Django 6.0.4 on 2026-04-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
                ('total_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='attended_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='alert',
            name='points_awarded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='assigned_doctor',
            field=models.CharField(default='Dr. Default', max_length=100),
            preserve_default=False,
        ),
    ]
